### ISSUE TITLE
Provide TCP-level examples that demonstrate ground-up Robot Capabilities

### ISSUE THREAD

**Issue by nowucca** [k3po/k3po#10]
We need a suite of basic RPT scripts that demonstrate TCP-level scripting.

The scripts should be commented clearly, and when presented demonstrate a progressive revelation of robot TCP functionality.

* start with a sample example (echo protocol) using netcat for client and for server
(hello world)
* present a regular expression match 
(hello <name>)
* change the protocol to respond with name (demonstrate named variables)
(hello <name> --> gday <name>)

Is there a resource/document showing what other features there are at the TCP level?

**Comment by dpwspoon** [comment]
Closing as there are now specification tcp module that shows all this
