### ISSUE TITLE
Provide HTTP-level examples that demonstrate ground-up Robot Capabilities

### ISSUE THREAD

**Issue by nowucca** [k3po/k3po#11]
We need a suite of basic RPT scripts that demonstrate HTTP-level scripting.

The scripts should be commented clearly, and when presented demonstrate a progressive revelation of robot HTTP functionality

First Examples
============

We should choose either GitHub API or an open API that requires no authentication (easier to test that way).  Perhaps Amazon S3 could serve - I'd like to choose a "good" RESTful-as-possible well-known API.

* script receipt of a GET request and issue a response (robot as server)
* script issue of a GET request and receipt of a response (robot as client)

* demonstrate a PUT (robot as server)
* demonstrate a PUT (robot as client)

* demonstrate a POST (robot as server)
* demonstrate a POST (robot as client)

Advanced Uses
=============
* Cache control headers to only fetch data if it has changed (etags, If-Modified-Since)

* WebSocket handshake, per RFC

We should be sure to include a possibly separate page for HTTP oddities, such as:
* chunked response format

**Comment by dpwspoon** [comment]
Closing as there are now specification http module that shows all this
