### ISSUE TITLE
Create K3poTestRule with same interface as K3poRule but without dependency on control protocol and k3po-maven-plugin 

### ISSUE THREAD

**Issue by dpwspoon** [k3po/k3po#117]
This will eliminate the need for the itests module by removing the dependency on k3po.java project (i.e. k3po.junit) and the k3po-maven-plugin.

**Comment by jfallows** [comment]
Agreed.  We'll also need something equivalent to the `@Specification` annotation.

Recommend we develop this in driver/src/test/java so as to avoid any confusion for end-users of `K3poRule`.
