### ISSUE TITLE
[HTTP Robot Lang] Query string with multiple parameters throws Syntax error

### ISSUE THREAD

**Issue by pkhanal** [k3po/k3po#118]
# Client Script
connect http://localhost:8080/path?.kr=1&.kb=256
connected

# Server Script
accept http://localhost:8080/path?.kr=1&.kb=256
accepted
connected

# Exception Thrown

line 24:72 token recognition error at: '&'
line 24:75 token recognition error at: '='
line 24:73 mismatched input 'kb' expecting {'bound', 'close', 'closed', 'connected', 'disconnected', 'opened', 'read', 'unbound', 'write'}
line 64:72 token recognition error at: '&'
line 64:75 token recognition error at: '='
line 64:73 mismatched input 'kb' expecting {'bound', 'close', 'closed', 'connected', 'disconnected', 'opened', 'read', 'unbound', 'write'}
line 99:71 token recognition error at: '&'
line 99:74 token recognition error at: '='
line 99:72 mismatched input 'kb' expecting {<EOF>, 'accept', 'accepted', 'bound', 'child', 'close', 'closed', 'connect', 'opened', 'property', 'read', 'unbind', 'unbound', 'write'}
line 141:71 token recognition error at: '&'
line 141:74 token recognition error at: '='
line 141:72 mismatched input 'kb' expecting {<EOF>, 'accept', 'accepted', 'bound', 'child', 'close', 'closed', 'connect', 'opened', 'property', 'read', 'unbind', 'unbound', 'write'}

[ERROR] Caught exception trying to parse script. Sending error to client
org.kaazing.k3po.lang.parser.ScriptParseException: org.kaazing.k3po.lang.parser.ScriptParseException: Syntax error while parsing: 
	at org.kaazing.k3po.lang.parser.ScriptParserImpl.parse(ScriptParserImpl.java:75)

**Comment by jfallows** [comment]
You can use the following syntax instead.
```
connect http://localhost:8080/path
connected
write parameter ".kr" "1"
write parameter ".kb" "256"
```
and
```
accept http://localhost:8080/path
accepted
connected
read parameter ".kr" "1"
read parameter ".kb" "256"
```
