### ISSUE TITLE
K3po maven-plugin can give better info level logging about current state

### ISSUE THREAD

**Issue by dpwspoon** [k3po/k3po#126]
We've got feedback from users that running `mvn k3po:start` is confusing because they assume k3po will remain running, so they are forgetting the `-Dmaven.k3po.daemon=false`.  To help them diagnose this problem we can log at the info level both the startup of k3po driver and the shutdown of the driver.

**Comment by dpwspoon** [comment]
We may also

**Comment by brennangaunce** [comment]
What's the use case for mvn k3po:start without the flag?  Are we confusing the goal for "start" with running the entire lifecycle during an external maven build?

In a test involving k3po, my expectation is that the build itself would call the start goal and the stop goal during the test lifecycle (even in the case of errors).

But yes - at the very least we should make it easier for the k3po user to understand what's going on, with a hint about the flag when run from maven.

**Comment by dpwspoon** [comment]
Your expectations are correct.  There are 2 goals start and stop which bind to pre-integration-test and post-integration-tests respectively.  

The issue is that any thread spawned by maven is shutdown when maven terminates, so the start goal reads the maven.k3po.daemon flag to indicate whether it should block maven from progressing/terminating.

So the goal "start" really has 2 use cases, one for when you are running in the maven lifecycle, and another for when you want to start k3po and leave it running.  The maven.k3po.daemon is the flag to indicate which one you want.
