### ISSUE TITLE
No http method in request causes k3po to timeout and report writes that never made it on the wire

### ISSUE THREAD

**Issue by dpwspoon** [k3po/k3po#129]
In

```
connect http://localhost:8080/
connected
write header "headerKey" "headerValue"
write flush
read header "headerKey2" "headerValue2"

accept http://localhost:8080/
accepted
connected
read header "headerKey" "headerValue"
write header "headerKey2" "headerValue2"
```
The result is
![screen shot 2015-02-12 at 1 44 06 pm](https://cloud.githubusercontent.com/assets/2014623/6177704/8deda9f2-b2bd-11e4-8a4c-ecece85707bf.png)

The http request never makes it on the wire.  We could throw an exception requiring an http method, or default to "GET".   I believe the original spec called for the latter, but I'm thinking requiring a method may be better.

Another alternative would be to randomize the method.

**Comment by dpwspoon** [comment]
If useful, I've Added a branch to reproduce on my [fork](https://github.com/dpwspoon/k3po).  Branch name is reproduces/129

**Comment by brennangaunce** [comment]
Let's not randomize the method.  Robot scripts are intended to be deterministic.  It will make debugging incredibly difficult.

Prefer that either the script always fail, or have the method default to GET (as spec'd).

Notice that we need a "write flush" to indicate that the http is finished.  Another possibility would be to use the syntax "write request" - which might be more readable.
