### ISSUE TITLE
Ability for http scripts to force a tcp close: abort command

### ISSUE THREAD

**Issue by dpwspoon** [k3po/k3po#132]
Forcing a premature tcp close from an http stream is required to test some of the requirements of RFC-7230 and RFC-7231 (http).  Authoring these tests in straight tcp semantics makes them brittle, as different implementations may order them in different ways.

**Comment by cmebarrow** [comment]
Two test cases in ConnectionManagementIT in specification/http are currently ignored because of this bug.

**Comment by cmebarrow** [comment]
This is also needed to complete the wse specification tests. Transport being closed is needed for some edge cases.

**Comment by cmebarrow** [comment]
Just had a discussion with @jfallows. We came up with the following proposal:

* Add a new `abort` command, which means to abort or reset the current connection
* Add a new `aborted` event, which can be used on the other side of the connection to verify the connection was aborted by the other end

For Http the implementation would be to close the TCPConnection in the case of abort, and (in HttpChildChannelSource) convert TCP closed event to aborted on the http pipeline.

Implementation steps:

* Add abort plus aborted to grammar and parsing and visitors
* AbortHandler plus AbortedHandler
* Alter HttpChildChannelSource to convert  TCP closed event to aborted on the http pipeline
* Alter HttpChildChannelSink to convert abort to tcp close

**Comment by sbadugu** [comment]
This issue was moved to kaazing/roadmap#670

**Comment by cmebarrow** [comment]
This has now been implemented, see https://github.com/k3po/k3po/pull/303
