### ISSUE TITLE
support negative matches for header value based on an EL variable

### ISSUE THREAD

**Issue by pkhanal** [k3po/k3po#143]
In many cases, we need to assert negative match for header value based on an EL variable. 
In the example script shown below, the script captures the **X-Sequence-No** header value in an EL variable **sequence** and the script needs to assert the subsequent request has the value of **X-Sequence-No** header ANYTHING EXCEPT **sequence + 1**.

accept http://localhost:8080/path/;e/cb?query
accepted
connected

read method "POST"
read version "HTTP/1.1"
read header "X-WebSocket-Version" "wseb-1.1"
read header "X-Sequence-No" /(?<sequence>\b[0-9]{1,3}\b)/
read closed

write status "201" "Created" 
write version "HTTP/1.1"
write header "X-WebSocket-Version" "wseb-1.1"
write header "Content-Type" "text/plain;charset=utf-8"
write header content-length

write "http://localhost:8080/path/QD12TQhXT6I5KeCrDe6g0IC9qoDkIioh\n"
write "http://localhost:8080/path/T4hpc2vqXueYRyyl3dIQw5K64XLQxuf1\n"
write close

accept http://localhost:8080/path/T4hpc2vqXueYRyyl3dIQw5K64XLQxuf1
accepted
connected

read await CREATED
read method "GET"
read version "HTTP/1.1"
**read header "X-Sequence-No" [ANYTHING EXCEPT sequence + 1]**
read closed

write status "400" "Bad Request" 
write header content-length
write close

**Comment by dpwspoon** [comment]
Thinking out loud here, but perhaps this could be solved with variable substitution and regex.  For example, the following regex matches anything but 1, `[^1]*`.  If we supported EL variables in expressions would that be sufficient?  Something like `[^${sequence}]*`.

Also, is the sequence number random or can it be deterministic per a test (always starting at 0 and incrementing)?

**Comment by dpwspoon** [comment]
@pkhanal solved this with an EL expression.
