### ISSUE TITLE
Multiple spaces between hex characters cause script parse errors

### ISSUE THREAD

**Issue by cmebarrow** [k3po/k3po#145]
Syntax like the following is rejected:

write [0x81  0xfe  0x00]

The error message is:
> [ERROR] Caught exception trying to parse script. Sending error to client. Due to org.kaazing.k3po.lang.parser.ScriptParseException:  
> org.kaazing.k3po.lang.parser.ScriptParseException: Syntax error while parsing:
line 42:6 token recognition error at: '[0x81  '

**Comment by cmebarrow** [comment]
This used to work in the previous version (robot).

**Comment by dpwspoon** [comment]
Should be an easy fix to Robot.g4

```
BytesLiteral
    : '[' (' ')? (ByteLiteral (' ')?)+ ']'
    ;
```

will become

```
BytesLiteral
    : '[' (' ')? (ByteLiteral (' ')*)+ ']'
    ;
```

**Comment by cmebarrow** [comment]
I'll take a shot at it
