### ISSUE TITLE
Specification.k3po.control - Enhance control protocol to support overriding default property values

### ISSUE THREAD

**Issue by dpwspoon** [k3po/k3po#154]
_From @jfallows on October 23, 2014 22:32_

Required by kaazing/robot#52.

_Copied from original issue: k3po/specification.k3po.control#1_

**Comment by dpwspoon** [comment]
_From @jfallows on October 23, 2014 22:37_

Propose updating the syntax for PREPARE to include property overrides in the body.

```
PREPARE
version:2.0
name:path/to/script/server
name:path/to/script/client
content-type:application/x-property-overrides
content-length:28

property message "override"
```
This assumes the resolved script has a section such as:

    property message "default"

Then the resolved script in PREPARED would show the overridden value.

```
PREPARED
content-length:220

property message "override"
...
```

This will let the test author see what was actually executed including overridden property values, not just the default values included in the original script before being overridden.

The content-type acts as a hint to describe the expected syntax and gives us an opportunity to evolve the protocol over time as needed.

**Comment by dpwspoon** [comment]
This looks good assuming the override properties in your examples are always strings.  Properties can include other values as well.  Meaning, the quote isn't required in the control protocol

```
property message "override"
property random  ${namespace:function()}
```

**Comment by dpwspoon** [comment]
_From @jfallows on October 24, 2014 0:57_

The intention is to support the same syntax as the main script for this section using the same grammar for properties.

```
PREPARE
version:2.0
name:path/to/script/server
name:path/to/script/client
content-type:application/x-property-overrides
content-length:38

property message [0x01 0x02 0x03 0x04]
```

Wouldn't we require the quotes to disambiguate between literal bytes and literal text for example?

Perhaps we need to update the content-type to match the script syntax used to read the properties.

**Comment by dpwspoon** [comment]
I think we are saying the same thing :-).  

I'm not familiar with the properties implementation, but couldn't we get an AstPropertyNode by calling something like parseProperty(String scriptLine) for each line in the control protocol Prepare.  That AstPropertyNode could then just be substituted for the AstPropertyNode on the first pass of the AST.  

That would imply that the syntax in the Prepare message would need to be identical to what it is in the script.  Such that it would be 

```
PREPARE
version:2.0
name:path/to/script/server
name:path/to/script/client
content-type:application/x-property-overrides
content-length:67

property message [0x01 0x02 0x03 0x04]
property message "override"
```

and NOT 

```
PREPARE
version:2.0
name:path/to/script/server
name:path/to/script/client
content-type:application/x-property-overrides
content-length:67

property message "[0x01 0x02 0x03 0x04]"
property message ""override""
```

the latter being what I wanted to make sure that we weren't doing...

**Comment by dpwspoon** [comment]
_From @jfallows on January 12, 2015 7:21_

Agreed.

**Comment by dpwspoon** [comment]
_From @jfallows on January 12, 2015 7:28_

The intent of this overridable properties enhancement is part of handling the re-targeting of logical and physical transports.

For example, suppose we had a set of AMQP 1.0 specification scripts authored using tcp://localhost:5672 and wanted to use them to test AMQP 1.0 in a browser over WebSocket.

This would benefit from syntax similar to the following:
`alias tcp://localhost:5672 ws://localhost:8080/amqp`

Similarly, we should probably be using `example.com` to author these scripts instead of  `localhost` and a similar aliasing mechanism would be:
`alias dns://example.com dns://localhost`, OR
`alias dns://example.com ip://127.0.0.1`

We need to be careful about going too far with parameterizing scripts with properties, otherwise we pretty soon have scripts that _require_ coordination on their exposed properties when configured externally just to get the scripts to work.

**Comment by dpwspoon** [comment]
_From @jfallows on January 12, 2015 8:51_

Logical DNS resolution would probably require a `NameResolver` abstraction at in `TcpBootstrapFactorySpi`.

**Comment by sbadugu** [comment]
This issue was moved to kaazing/roadmap#677
