### ISSUE TITLE
Specification.WSE - Spec tests for binary as text, binary as escaped text and binary as mixed text encodings

### ISSUE THREAD

**Issue by dpwspoon** [k3po/k3po#157]
_From @pkhanal on February 3, 2015 19:47_

_Copied from original issue: k3po/specification.wse#11_

**Comment by cmebarrow** [comment]
@dpwspoon It would be good to spell out the purpose of this bug. I presume it is to flesh out the tests in https://github.com/k3po/k3po/tree/develop/specification/wse/src/main/scripts/org/kaazing/specification/wse/data/binary.as.escaped.text and https://github.com/k3po/k3po/tree/develop/specification/wse/src/main/scripts/org/kaazing/specification/wse/data/binary.as.text to match those in https://github.com/k3po/k3po/tree/develop/specification/wse/src/main/scripts/org/kaazing/specification/wse/data/binary ?

**Comment by dpwspoon** [comment]
@cmebarrow I believe that is correct
