### ISSUE TITLE
specification: physical binds and connects

### ISSUE THREAD

**Issue by jitsni** [k3po/k3po#197]
accept-option
- to bind on specific ip/interface+port

connect-option
- to connect to resolvable host+port

This is required for http reverse proxy script where reverse proxy connects to different host. For example:
connect http://example.com:80
connect-option internal.example.com:3333

The proxy connects to internal.example.com:3333, but sends Host: example.com:80 header

**Comment by sbadugu** [comment]
[Fixed here](https://github.com/k3po/k3po/pull/198)

**Comment by sbadugu** [comment]
@dpwspoon Please close this issue. Thanks.
