### ISSUE TITLE
httpxe specification tests notably in RequestsIT and OriginSecurityIT sometimes fail due to failed connect stream

### ISSUE THREAD

**Issue by cmebarrow** [k3po/k3po#229]
See for example [k3po Travils build #332.1](https://travis-ci.org/k3po/k3po/jobs/84894172). The test failed as follows:
```
Running org.kaazing.specification.httpxe.RequestsIT
Tests run: 17, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.989 sec <<< FAILURE! - in org.kaazing.specification.httpxe.RequestsIT
shouldProcessPathEncodedPostRequestAsOptionsRequest(org.kaazing.specification.httpxe.RequestsIT)  Time elapsed: 0.07 sec  <<< FAILURE!
org.junit.ComparisonFailure: Specified behavior did not match expected:<[connect http://localhost:8000/;options/path
connected

write method "POST"
write version "HTTP/1.1"
write header content-length
write flush]

accept http://loca...> but was:<[]

accept http://loca...>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.kaazing.k3po.junit.rules.SpecificationStatement.evaluate(SpecificationStatement.java:127)
	at org.junit.rules.Verifier$1.evaluate(Verifier.java:35)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
```

**Comment by mgherghe** [comment]
There are also other httpxe tests failing on Travis builds. See builds: [#319.1](https://travis-ci.org/k3po/k3po/jobs/84051138),  [#319.2](https://travis-ci.org/k3po/k3po/jobs/84051141), [#322.2](https://travis-ci.org/k3po/k3po/jobs/84279223), [#324.1](https://travis-ci.org/k3po/k3po/jobs/84325616), all with the same error message as above.

**Comment by cmebarrow** [comment]
Same failure occurred multiple times in [this](https://travis-ci.org/cmebarrow/k3po/builds/90592278) Travis build, console output is available at:
[build33_diagnostics_httpxe_fail_k3o_issue_229.txt](https://files.zenhub.io/5643ae4ee5b473fe074acef2)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)
