### ISSUE TITLE
Some WSE specification tests are not usable in practice because upstream requests may legitimately vary

### ISSUE THREAD

**Issue by cmebarrow** [k3po/k3po#232]
There are many different ways to send upstream data without violating the [WSE specification](https://github.com/k3po/k3po/blob/develop/specification/wse/SPEC.md). For example, if a client application creates a WebSocket connection, then sends data twice, then closes the WebSocket, this may legitimately be expressed as everything from one to three distinct upstream HTTP requests, and indeed what happens in practice will just depend on timing, for example, when using the JavaScript client it all depends when the upstream XMLHttpRequest enters ready state 4. The two sends will be enqueued then the CLOSE will be enqueued, and all will be sent in a single upstream request if ready state 4 is reached after they have all been put on the queue. But there will be multiple upstream requests if  ready state 4 is reached before all the items have been placed on the queue.

This means that in practice it will be difficult for client tests (and WsebConnector tests) to use those response scripts which involve upstream data, for example [org/kaazing/specification/wse/data/binary/echo.payload.length.127/response.rpt](https://github.com/k3po/k3po/blob/develop/specification/wse/src/main/scripts/org/kaazing/specification/wse/data/binary/echo.payload.length.127/response.rpt)

**Comment by cmebarrow** [comment]
It is possible to change the above cited example to be usable with WsebConnector by removing (commenting out) the lines making assumptions that may not be valid:
```
read await CREATE_COMPLETED
read method "POST"
read version "HTTP/1.1"
read header "Content-Type" "application/octet-stream"
read header "X-Sequence-No" ${wse:asString(sequence + 1)}

read [0x80 0x7F]
read ([0..127] :server127)
#read [0x01 0x30 0x31 0xFF]
read notify DATA_RECEIVED
#read closed

#write status "200" "OK"
#write version "HTTP/1.1"
#write header content-length
#write close
```

**Comment by jfallows** [comment]
Is the RECONNECT frame actually required on the upstream for the test to validate correctness?

**Comment by jfallows** [comment]
Haha, looks like we might have been thinking the same thing here... :smile:

**Comment by cmebarrow** [comment]
Plan to fix:
Update scripts to avoid assuming RECONNECT will be included on upstream (started on my branch wse_spec_script_fixes_issue_232)

**Comment by cmebarrow** [comment]
Fixed by PR https://github.com/k3po/k3po/issues/234
