### ISSUE TITLE
Add new command to k3po to execute clean up from junit rule.

### ISSUE THREAD

**Issue by dpwspoon** [k3po/k3po#239]
I believe the assumption when creating K3po was that the cleanup of K3po was executed in k3po.finish() call.  However this is not exactly correct

Currently we call Robot.destroy() from the ControlServerHandler channelClosed

```java
    @Override
    public void channelClosed(ChannelHandlerContext ctx, ChannelStateEvent e) throws Exception {
        if (robot != null) {
            robot.destroy();
        }
        channelClosedFuture.setSuccess();
        ctx.sendUpstream(e);
    }

```

K3po.destroy releases the external resources used by the bootstrap factory

```java
    public boolean destroy() {

        if (destroyed) {
            return true;
        }

        abort();

        if (createdBootstrapFactory) {
            try {
                bootstrapFactory.shutdown();
                bootstrapFactory.releaseExternalResources();
            }
            catch (Exception e) {
                if (LOGGER.isDebugEnabled()) {
                    LOGGER.debug("Caught exception releasing resources", e);
                }
                return false;
            }
        }

        return destroyed = true;
    }
```

I believe this may cause a race between the release of external resources and the starting of a next test, which could manifest itself like this https://github.com/k3po/k3po/issues/229

We could clean up the bound channel resources on the k3po.finish (releaseExternalResources there), but logically I think this would be better done when the rule chain is returning.

I propose synchronizing the shutdown of k3po driver with a new command and event.
For now we will call these
`TERMINATE` and `TERMINATED` respectively.  (These are okay, looking for something better if there is something)

Terminate will be sent from the K3poRule after the test logic has executed and is returning out of the chain (perhaps in the verify() call)

**Comment by dpwspoon** [comment]
Additionally, if clean up of a k3po accept is done at K3po.finish, this can causes junit code to observer behavior not specificed in the script (such as a close).  Meaning an assert or mock might have unexpected behavior

**Comment by dpwspoon** [comment]
reviewed with @jfallows.  Sounds good, though perhaps we could have better verbs then terminate and terminated.  Perhaps clean and cleaned.  Terminate is sort of alright though cause you are terminating the k3po.driver class (K3po)

**Comment by cmebarrow** [comment]
@dpwspoon Are you saying connections established by the Robot (via connect and accept) will remain open unless explicitly closed in scripts until terminate (or clean) is sent? I think that will resolve many sporadic test failures we've seen, including in tests like the jms tests that use mock objects, as you pointed out above.
