### ISSUE TITLE
specification/http build failing sporadically in some tests with expected read closed got disconnected

### ISSUE THREAD

**Issue by cmebarrow** [k3po/k3po#251]
This is similar to #222 although that one was for TCP case. Example output with k3po debug messages (from a run on my work laptop):
[out.bbosh_http_and_deps_only.txt](https://github.com/k3po/k3po/files/25689/out.bbosh_http_and_deps_only.txt)

Same failure is frequently seen on Travis builds.

Extract from the build output:
```
Failed tests: 
  MessageFormatIT.headResponseMustNotHaveContentThoughMayHaveContentLength Specified behavior did not match expected:<...ntent-Length" "100"
[read clos]ed

accept http://lo...> but was:<...ntent-Length" "100"
[disconnect]ed

accept http://lo...>
```

**Comment by a-zuckut** [comment]
I believe I fixed this test with https://github.com/k3po/k3po/pull/343, but it might continue to be a sporadic failure.

**Comment by cmebarrow** [comment]
Closing on assumption #343 has fixed it. Please re-open if the problem recurs.
