### ISSUE TITLE
Validating a strong entity tag using a regular expression does not work

### ISSUE THREAD

**Issue by sanjay-saxena** [k3po/k3po#253]
[RFC 7232](https://tools.ietf.org/html/rfc7232) allows specifying **strong** entity-tag as the value of `ETag` HTTP header like this:

```
HTTP/1.1 200 OK
...
ETag: "9c44de29868303b5ad7a8fafd21e98f9"
...
```
Where as a **weak** entity-tag has a `W/` prefix and looks like this:

```
HTTP/1.1 200 OK
...
ETag: W/"9c44de29868303b5ad7a8fafd21e98f9"
...
```

In a K3PO script, I would like to validate the **strong** entity tag when it is being read into a variable like this:

```
read header "ETag" /(?<etag>^\".*?\"$)/
```

However, when a **weak** entity tag is used, K3PO does not barf at the aforementioned line.

If there are other ways to accomplish this, it would be good to know.

**Comment by a-zuckut** [comment]
The way to fix this issue is to utilize the RegEx syntax [^W] which tells k3po that checks for not having the start of a weak header.

The expression: ``` read header "ETag" /(?<etag>^[^W]\".*\"$)/ ```
