### ISSUE TITLE
K3po Abort command races backlogged messages.

### ISSUE THREAD

**Issue by dpwspoon** [k3po/k3po#332]
When K3po driver receives an abort it asks for a hard stop of all pipelines.  Any handler such has read handlers that have not processed their ChannelFuture (i.e. it is in a incomplete state) throws a ScriptProgress exception.  I have debugged a few tests today where the bytes to a readHandler had arrived on the wire but were still being processed, causing an abort to fail the test when it shouldn't of.  These tests where running with small junit timeouts (1 to 1.5 secs) and where sending either large number of bytes (65535 for example) or having numerous read handlers.  The easy work around to this is to set the timeout to be larger.  But it would be optimal if k3po allowed all buffered data on the upstream to be flushed before checking for script progress.

**Comment by dpwspoon** [comment]
I took a shot at doing this and think that theoretically we could create a new channel event (dispose or k3po-abort) that we send on the upstream pipeline when an abort is received.  If it comes out the other end then I think via the current threading model all other messages will have been scheduled before the new channel event.

**Comment by dpwspoon** [comment]
I think instead of a heavy duty work around mechanism we should explain the timeout issue in the diff. To do this we should have the abort command from junit be allowed to attach an optional reason that appears in the diff

**Comment by dpwspoon** [comment]
TODO for this task have been added to ScriptRunner.java

**Comment by sbadugu** [comment]
We are not going to fix this issue.

**Comment by dpwspoon** [comment]
The abort is the last fall back mechanism, if a test is requesting an abort something went wrong.  The time out should be increased

**Comment by sbadugu** [comment]
@dpwspoon While running `gateway Plan C`, I encountered the following in the log messages:

>
K3po Script Runner is sending an abort!
 Aborts may cause K3po to falsely fail the test if K3po
is still processing a backlog of messages.  This is often the case in junit tests that have low
timeout exceptions (less than 5 secs) and are running on somewhat limited hardware (travis CI and build machines)
see https://github.com/k3po/k3po/issues/332 for more details
[INFO] ABORT
>

Can you please confirm if we can remove the link to the bug on second last line ?
