### ISSUE TITLE
K3po driver is stuck if an abort is sent after an await on a barrier never triggered

### ISSUE THREAD

**Issue by StCostea** [k3po/k3po#388]
If there is an await on a barrier that is never triggered, calling an abort will block the thread on waiting the barrier to be triggered. 
The following protocol commands will make the driver unresponsive:

```
PREPARE
version:2.0
name:org/kaazing/specification/control/assets/server
name:org/kaazing/specification/control/assets/client.with.barriers

AWAIT
barrier:NOTIFYING_BARRIER

ABORT

```
In the script `client.with.barriers`, the NOTIFYING_BARRIER is never notified.
The cause is the code in the listener `whenAbortedOrFinished `in class `ControlServerHandler`.

**Comment by StCostea** [comment]
I am not sure what is the purpose of awaiting on all barriers before finishing. So I'm not sure how to fix it.

**Comment by dpwspoon** [comment]
>  I am not sure what is the purpose of awaiting on all barriers before finishing. So I'm not sure how to fix it.

This sounds like an implementation bug to me, and probably it should not be implemented this way.

**Comment by StCostea** [comment]
I have currently commented the await part in the listener. So we are just sending the FINISHED event. Is this ok as a solution ? 
With this code all specification tests are passing.
