### ISSUE TITLE
Test in http specification - ConnectionManagementIT - fails in specific conditions

### ISSUE THREAD

**Issue by StCostea** [k3po/k3po#395]
Test ConnectionManagementIT#clientWithPipeliningMustNotRetryPipeliningImmediatelyAfterFailure is successful in Eclipse and in 'mvn install' under Windows, but fails under Ubuntu for 'mvn install'. Also, running a single test in Ubuntu, but with external K3po driver is successful.

The cause is a race condition between two connections to a server. It seems that in that specific condition, the second connection reaches the server before the first one and the responses are not the expected ones.

The fix is to add an additional step before notifying the barrier for the second connection - closed connection for the first one.

**Comment by StCostea** [comment]
It seems I missed to make the PR...
https://github.com/k3po/k3po/pull/410

**Comment by StCostea** [comment]
This is a capture with the problem under Ubuntu
[ConnectionManagementIT_pcap.zip](https://github.com/k3po/k3po/files/827638/ConnectionManagementIT_pcap.zip)

**Comment by Anisotrop** [comment]
@dpwspoon Hi David, we have 2 ways to address the issue, one would be to simply add the closed check the other would be to manage the connections at tcp level. They are implemented by the connected PRs.
