### ISSUE TITLE
TLS/SSL support

### ISSUE THREAD

**Issue by dpwspoon** [k3po/k3po#93]
Support TLS/SSL as a transport.

For example:

```
accept tls://localhost:8080
accepted
connected
read ...
write ...
close
closed

connect tls://localhost:8080
connected
read ...
write ...
close
closed
```

**Comment by jfallows** [comment]
This requires us to support a keystore and truststore, logically a dependency of the script.

If we also make it possible to override the location such that the hostname (and therefore the required certificate) is different, then we'd need to let the keystore and truststore be overridden and resolved locally too.

**Comment by jfallows** [comment]
We'll also need various options to control aspects of the TLS handshake, such as protocol version, cipher suites, client certificate etc.

**Comment by krismcqueen** [comment]
The HTTP 2.0 spec (https://tools.ietf.org/html/draft-ietf-httpbis-http2-16) dictates specific semantics for negotiating HTTP2 over TLS.  The connection negotiation uses the ALPN extension (https://tools.ietf.org/html/rfc7301), so it would be nice if ALPN where also available as part of K3PO's TLS support.
